customer_name=input("please enter your full name : ")
prod_name=input("please enter the product name : ")
price=float(input("please enter the price of the product : "))
quantity=int(input("please enter the quantity of the product : "))
total=price*quantity
print("=====================================")
print("\t RECEIPT")
print("=====================================")
print("Customer :"+ customer_name)
print("-------------------------------------")
print("product \t Price  \t Qity")
print(f"{prod_name}\t{price} ETB\t{quantity}")
print(f"Total : {total} ETB")
print("Thank you for shopping!")
print("======================================")